<a href="https://colab.research.google.com/github/phlapapon-kulto/PythonDataViz2026/blob/main/Hw5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


### เขียน function คูณ matrix แล้ว test กับ matrix ขนาด
### (2,3)*(3,2)
### (4,4)*(4,1)
### (2,2)*(2,2)

In [ ]:
import numpy as np

In [ ]:
def mat_mul(mat_a, mat_b):
  try:
    result = np.dot(mat_a, mat_b)
    return result
  except ValueError as e:
    return f"Error: {e}. Check matrix dimensions for compatibility."

In [ ]:
# (2,3) * (3,2)
print("\n--- Test Case 1: (2,3) * (3,2) ---")
mat_2x3 = np.array([[1, 2, 3], [4, 5, 6]])
mat_3x2 = np.array([[7, 8], [9, 1], [2, 3]])

print("Matrix (2x3):\n", mat_2x3)
print("Matrix (3x2):\n", mat_3x2)
result_1 = mat_mul(mat_2x3, mat_3x2)
print("Result (2x2):\n", result_1)

# (4,4) * (4,1)
print("\n--- Test : (4,4) * (4,1) ---")
mat_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 0, 1, 2], [3, 4, 5, 6]])
mat_4x1 = np.array([[10], [11], [12], [13]])

print("Matrix (4x4):\n", mat_4x4)
print("Matrix (4x1):\n", mat_4x1)
result_2 = mat_mul(mat_4x4, mat_4x1)
print("Result (4x1):\n", result_2)

# (2,2) * (2,2)
print("\n--- Test : (2,2) * (2,2) ---")
mat_2x2_a = np.array([[1, 2], [3, 4]])
mat_2x2_b = np.array([[5, 6], [7, 8]])

print("Matrix (2x2):\n", mat_2x2_a)
print("Matrix (2x2):\n", mat_2x2_b)
result_3 = mat_mul(mat_2x2_a, mat_2x2_b)
print("Result (2x2):\n", result_3)


--- Test Case 1: (2,3) * (3,2) ---
Matrix (2x3):
 [[1 2 3]
 [4 5 6]]
Matrix (3x2):
 [[7 8]
 [9 1]
 [2 3]]
Result (2x2):
 [[31 19]
 [85 55]]

--- Test : (4,4) * (4,1) ---
Matrix (4x4):
 [[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]
 [3 4 5 6]]
Matrix (4x1):
 [[10]
 [11]
 [12]
 [13]]
Result (4x1):
 [[120]
 [304]
 [128]
 [212]]

--- Test : (2,2) * (2,2) ---
Matrix (2x2):
 [[1 2]
 [3 4]]
Matrix (2x2):
 [[5 6]
 [7 8]]
Result (2x2):
 [[19 22]
 [43 50]]
